export const ASYNC_ACTION_START = 'common/ASYNC_ACTION_START';
export const ASYNC_ACTION_END = 'common/ASYNC_ACTION_END';

export const LOAD_STUDENTS_STATISTICS_SUCCESS = 'student/LOAD_STUDENTS_STATISTICS_SUCCESS';
export const LOAD_STUDENTS_STATISTICS = 'student/LOAD_STUDENTS_STATISTICS';
